### ISSUE TITLE
collective.listingviews listing views controlpanel broken on Plone 4.3.x - item fields and listing fields widgets missing data

### ISSUE THREAD

**Issue by pigeonflight** [collective/collective.listingviews#17]
On a brand new Plone 4.3.6 site with only collective.listingviews as an add-on in the buildout.
After installing collective.listingviews to my Plone site when I navigate to the listing views controlpanel I see this (note that the "Item fields" and "listing fields" widgets are empty:
![listing views control panel](https://cloud.githubusercontent.com/assets/31827/9559353/be9aae8e-4db7-11e5-9d72-ab54656d83bc.png)

More details on this issue are documented here:
https://community.plone.org/t/collective-listingviews-item-fields-and-listing-fields-empty-in-listing-views-control-panel/908

**Comment by Robynstar** [comment]
I can confirm this, brand new blank 4.3.6 site has empty field choice widgets for constructing a new view.

**Comment by pigeonflight** [comment]
@Robynstar thanks for this. Closing this bug as won't fix.
Thanks for the reference to the fix.
